const getFacets = function(zenodeo) {
    return [
        {   "key": "title",
            "actualKey": "title", 
            "values": [], 
            "prompt": "Enter text to search in the 'title' field",
            "noDuplicates": true },
        {   "key": "authors", 
            "actualKey": "creators.name",
            "values": `${zenodeo}/v1/authors`, 
            "prompt": "Type at least three letters to get authors",
            "noDuplicates": true },
        {   "key": "keywords", 
            "actualKey": "keywords",
            "values": `${zenodeo}/v1/keywords`, 
            "prompt": "Type at least three letters to get keywords",
            "noDuplicates": false },
        {   "key": "families", 
            "actualKey": "title",
            "values": `${zenodeo}/v1/families`, 
            "prompt": "Type at least three letters to get families",
            "noDuplicates": true },
        {   "key": "taxa", 
            "actualKey": "title",
            "values": `${zenodeo}/v1/taxa`, 
            "prompt": "Type at least three letters to get taxa",
            "noDuplicates": true },
        {   "key": "year", 
            "actualKey": "publicationdate",
            "values": [], 
            "prompt": "Enter year to get publications from that year",
            "noDuplicates": true }
    ]
}